name: DeepSource_Test_Coverage
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    # Generate coverage report in xml format coverage xml

    - name: Install pytest and pytest-cov pacakages from pip
      run:
        pip install pytest pytest-cov

    - name: Run pytest with --cov and --cov-report flags
      run:
        python -m pytest --cov=./ --cov-report xml

    - name: Install deepsource CLI
      run:
        curl https://deepsource.io/cli | sh

    - name: From the root directory, run the report coverage command
      run:
        ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml

      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
